"""
Task 2 E3 Stage 1: synthetic ROCStories-style distillation starting from the current E2 checkpoint.

This stage uses a high-quality synthetic short-story corpus generated by a stronger model.
The goal is to distill cleaner ROC-style event structure and endings into the small model
before a final ROCStories polish stage.
"""

out_dir = "out-task2-e3-synth-distill"
init_from = "resume_path"
resume_ckpt_path = "out-task2-e2-storyaware-polish/ckpt.pt"

eval_interval = 25
eval_iters = 100
log_interval = 10
always_save_checkpoint = True

wandb_log = False
wandb_project = "rocstories"
wandb_run_name = "task2-e3-stage1-synth-distill"

dataset = "rocstories_synth"
gradient_accumulation_steps = 1
batch_size = 80
sampling_mode = "mixed"
story_sampling_prob = 0.85
opening_window_tokens = 12

block_size = 96
n_layer = 6
n_head = 6
n_embd = 384
dropout = 0.14

learning_rate = 1.0e-4
weight_decay = 7e-2
max_iters = 14500
lr_decay_iters = 14500
min_lr = 1e-5
beta2 = 0.99
warmup_iters = 100

compile = False
seed = 2027
